version: '3'
services:
  db:
    image: postgres:11
    volumes:
      - $HOME/docker/volumes/postgres-classes:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_HOST_AUTH_METHOD: trust
    restart: always
    ports:
      - "5432:5432"